# Generated by Django 3.0.2 on 2020-05-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output_audios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_1', models.FileField(upload_to='media')),
                ('search_2', models.FileField(upload_to='media')),
                ('search_3', models.FileField(upload_to='media')),
                ('search_4', models.FileField(upload_to='media')),
                ('search_5', models.FileField(upload_to='media')),
                ('search_6', models.FileField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='input_audios',
            name='search_1',
        ),
        migrations.RemoveField(
            model_name='input_audios',
            name='search_2',
        ),
        migrations.RemoveField(
            model_name='input_audios',
            name='search_3',
        ),
        migrations.RemoveField(
            model_name='input_audios',
            name='search_4',
        ),
        migrations.RemoveField(
            model_name='input_audios',
            name='search_5',
        ),
        migrations.RemoveField(
            model_name='input_audios',
            name='search_6',
        ),
    ]
