# Generated by Django 3.0.2 on 2020-05-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='aud2_response',
            field=models.TextField(default='match', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='aud3_response',
            field=models.TextField(default='match', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='aud4_response',
            field=models.TextField(default='match', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='aud5_response',
            field=models.TextField(default='match', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='aud6_response',
            field=models.TextField(default='match', max_length=20),
            preserve_default=False,
        ),
    ]
