# Generated by Django 3.0.2 on 2020-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0004_auto_20200511_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_audios',
            name='keyword',
            field=models.TextField(default='sample', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output_audios',
            name='keyword',
            field=models.TextField(default='sample', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='keyword',
            field=models.TextField(default='sample', max_length=20),
            preserve_default=False,
        ),
    ]
