# Generated by Django 3.0.2 on 2020-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0005_auto_20200514_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='output_audios',
            name='visual_1',
            field=models.FileField(default='default', upload_to='media'),
            preserve_default=False,
        ),
    ]
