# Generated by Django 3.0.2 on 2020-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0008_auto_20200516_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_audios',
            name='chroma',
            field=models.FloatField(default=0.08),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input_audios',
            name='melspec',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input_audios',
            name='silence_decible_floor',
            field=models.FloatField(default=0.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input_audios',
            name='zerocross',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
