# Generated by Django 3.0.2 on 2020-05-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0009_auto_20200517_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input_audios',
            old_name='melspec',
            new_name='malspec',
        ),
    ]
