# Generated by Django 3.0.2 on 2020-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0011_input_audios_window_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='output_audios',
            name='runtime',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
