# Generated by Django 3.0.2 on 2020-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0013_plotter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchkeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchkey', models.TextField(max_length=20)),
            ],
        ),
    ]
