# Generated by Django 3.0.2 on 2020-06-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0016_auto_20200614_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output_audios',
            name='end_time',
            field=models.IntegerField(default=1000),
        ),
    ]
