# Generated by Django 3.0.2 on 2020-06-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyserapp', '0017_auto_20200614_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='output_audios',
            name='test_audio',
            field=models.TextField(default='abcd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='output_audios',
            name='end_time',
            field=models.IntegerField(),
        ),
    ]
